-- Motor's Events — base Supabase
-- À exécuter dans Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  bio text default '',
  city text default '',
  region text default '',
  avatar_url text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  organizer_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 3 and 160),
  category text not null,
  event_type text default '',
  starts_at timestamptz not null,
  ends_at timestamptz,
  city text not null default '',
  region text not null default '',
  address text default '',
  description text not null default '',
  official_url text,
  image_url text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_id bigint not null references public.events(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, event_id)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    nullif(split_part(coalesce(new.email,''), '@', 1), ''),
    nullif(split_part(coalesce(new.email,''), '@', 1), '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.events enable row level security;
alter table public.favorites enable row level security;

drop policy if exists "profiles public read" on public.profiles;
create policy "profiles public read" on public.profiles
for select using (true);

drop policy if exists "profiles own insert" on public.profiles;
create policy "profiles own insert" on public.profiles
for insert with check (auth.uid() = id);

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles
for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "events public approved read" on public.events;
create policy "events public approved read" on public.events
for select using (status = 'approved' or organizer_id = auth.uid() or public.is_admin());

drop policy if exists "events authenticated create" on public.events;
create policy "events authenticated create" on public.events
for insert to authenticated
with check (organizer_id = auth.uid() and status = 'pending');

drop policy if exists "events owner update pending" on public.events;
create policy "events owner update pending" on public.events
for update to authenticated
using (organizer_id = auth.uid() and status = 'pending')
with check (organizer_id = auth.uid() and status = 'pending');

drop policy if exists "events owner delete" on public.events;
create policy "events owner delete" on public.events
for delete to authenticated
using (organizer_id = auth.uid() or public.is_admin());

drop policy if exists "events admin moderate" on public.events;
create policy "events admin moderate" on public.events
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "favorites own" on public.favorites;
create policy "favorites own" on public.favorites
for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true), ('event-images', 'event-images', true)
on conflict (id) do nothing;

-- Pour une première version, les images sont publiques en lecture,
-- mais l'écriture est limitée au dossier portant l'UUID de l'utilisateur.
drop policy if exists "avatar upload own folder" on storage.objects;
create policy "avatar upload own folder" on storage.objects
for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatar update own folder" on storage.objects;
create policy "avatar update own folder" on storage.objects
for update to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatar delete own folder" on storage.objects;
create policy "avatar delete own folder" on storage.objects
for delete to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "event image upload own folder" on storage.objects;
create policy "event image upload own folder" on storage.objects
for insert to authenticated
with check (bucket_id = 'event-images' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "event image update own folder" on storage.objects;
create policy "event image update own folder" on storage.objects
for update to authenticated
using (bucket_id = 'event-images' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "event image delete own folder" on storage.objects;
create policy "event image delete own folder" on storage.objects
for delete to authenticated
using (bucket_id = 'event-images' and (storage.foldername(name))[1] = auth.uid()::text);
